name: 'Send SMS Notification with Twilio'
description: 'Sends an SMS notification with date, time, workflow name, repo name and repo owner'
inputs:
  TWILIO_ACCOUNT_SID:
    description: 'Twilio Account SID found in Twilio console.'
    required: true
  TWILIO_AUTH_TOKEN:
    description: 'Twilio Auth Token found in Twilio console'
    required: true
  TWILIO_PHONE_NUMBER:
    description: 'Twilio phone number to send messages from.'
    required: true
  PHONE_NUMBER:
    description: 'Phone number to send messages to.'
    required: true
  withDate:
    description: 'Include date with message'
    required: false
    default: true
  withTime:
    description: 'Include time with message'
    required: false
    default: true
  withRepoName:
    description: 'Include repository name'
    required: false
    default: true
  withRepoOwner:
    description: 'Include repository owner'
    required: false
    default: true
  note:
    description: 'Additional note to include with message.'
    required: false
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'