name: Testing SMS Notification
on:
  schedule:
    # Runs at 12 AM est
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  test:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        id: testing
        uses: ammar-ahmed22/SendSMSNotification@v1.0-beta
        with:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
          PHONE_NUMBER: '+14168364386'